// <auto-generated />
namespace MailsApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class IsCheckedAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IsCheckedAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "202210131923346_IsCheckedAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
